version: '3.8'

services:
  medication-bot:
    build: .
    container_name: med-reminder-bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Kiev
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app/data:/app/data
      - ./app/config:/app/config
      - ./app/logs:/app/logs
      - ./app/backups:/app/backups
    mem_limit: 512m
    cpus: 0.5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('data/database.db').execute('SELECT 1')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s